---
- name: Redis server with daily backups configured
  hosts: redis
  user: ubuntu
  vars_files:
    - vars/redis.yml
    - vars/secrets.yml
  roles:
    - common
    - { role: common_service_security, allow_port: "{{ redis.app_db_port }}" }
    - common_ssh_authorized_keys
    - redis
    - ruby
    - backup_user
    - backup_system
  
