---
- name: copy available hosts
  copy: src={{ item }} dest=/etc/nginx/sites-available/{{ item }} owner=root group=root
  sudo: yes
  tags:
    - nginx
  with_items:
    - ad.venture.io
    - adv.io
    - blog.venture.io
    - get.adv.io
    - gridkick.com
    - staging.ad.venture.io
    - staging.gridkick.com
    - venture.io
    - local.gridkick.com

- name: link enabled hosts
  file: src=/etc/nginx/sites-available/{{ item }}
        dest=/etc/nginx/sites-enabled/{{ item }}
        state=link
  sudo: yes
  with_items:
    - ad.venture.io
    - adv.io
    - blog.venture.io
    - get.adv.io
    - gridkick.com
    - staging.ad.venture.io
    - staging.gridkick.com
    - venture.io
    - local.gridkick.com

- name: restart nginx
  service: name=nginx state=restarted
  tags:
    - nginx
  sudo: yes
