---
- name: update apt cache
  sudo: yes
  apt:  update_cache=yes 
        cache_valid_time=3600

- name: install mysql packages
  sudo: yes
  apt:  pkg={{ item }} state=present
  with_items:
    - mysql-server={{ mysql.version }}
    - mysql-client
    - python-mysqldb

- name: set mysql root password
  sudo: yes
  mysql_user: name=root 
              host=localhost 
              password={{ mysql_root_password }}
  

- name: copy bind_address.cnf file with wildcard bind address
  sudo: yes
  copy: src=bind_address.cnf 
        dest=/etc/mysql/conf.d/bind_address.cnf 
        owner=root 
        mode=0600

- name: copy port.cnf file with custom server port
  sudo: yes
  template: src=port.cnf.j2 
            dest=/etc/mysql/conf.d/port.cnf 
            owner=root 
            mode=0600  

- name: copy .my.cnf file with root password credentials
  sudo: yes
  template: src=my.cnf.j2 
            dest=~/.my.cnf 
            owner=root 
            mode=0600

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: name=root 
              host={{ item }} 
              password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  sudo: yes
  mysql_user: name='' 
              host={{ item }} 
              state=absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: remove the test database
  sudo: yes
  mysql_db: name=test 
            state=absent

- name: add default user
  sudo: yes
  mysql_user: name="{{ mysql_user }}" 
              password="{{ mysql_root_password }}"
              host=% 
              priv=*.*:ALL 
              state=present

- name: restart mysql database
  sudo: yes
  service: name=mysql 
           state=restarted
