---
- name: create expected capistrano dirs
  sudo: yes
  file: name=/var/ops/adventure-deploy
        state=directory
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}
  tags:
    - capistrano
    - deploy

