---
- name: setup ssl cert directories
  sudo: yes
  file: name=/opt/nginx/conf/ssl
        state=directory
        owner=root
        group=root

- name: place adventure ssl cert files
  copy: src={{ item }}
        dest=/opt/nginx/conf/ssl/{{ item }}
        owner=root
        group=root
  sudo: yes
  with_items:
    - ad.venture.io-unified.crt
    - ad.venture.io.key
