---
- name: add ubuntu group
  group: name={{ group }}

- name: add user
  sudo: true
  user: name={{ user }} 
        group={{ group }} 
        shell=/bin/bash
        password=$1$adv99ADV$CDEtxC.VRXzdz.hkIw3.z1

- name: Add user to sudoers
  action: lineinfile 
          dest=/etc/sudoers 
          regexp="{{ user }} ALL" 
          line="{{ user }} ALL=(ALL) ALL" 
          state=present
    
- name: add public key to user authorized keys
  authorized_key: "user={{ user }} key='{{ item }}'"
  with_file:
    - westonplatter@gmail.com.pub
    - flynfish@gmail.com.pub

- name: allow user to ssh
  lineinfile: "dest=/etc/ssh/sshd_config regexp='AllowUsers {{ user }}' line='AllowUsers {{ user }}'"

- name: restart ssh
  service: name=ssh state=restarted
  
- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers 
          regexp="^%sudo" 
          state=absent

- name: disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config 
          regexp="^PermitRootLogin" 
          line="PermitRootLogin no" 
          state=present

- name: restart ssh
  service: name=ssh state=restarted
  ignore_errors: yes
  
